name: meesign_native
description: Dart wrappers around MeeSign Rust and C++ libraries.
version: 0.3.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  ffi: ^2.0.2
  native_assets_cli: ^0.5.4

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.16.0
